version: '3'

services:
  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app/
  #     - ./node_modules:/usr/app/node_modules
  #   depends_on:
  #     - database

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db_users
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
